'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17351
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class DateTime_EditField
    Protected Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected Label1 As Global.System.Web.UI.WebControls.Label    
    Protected TextBox1 As Global.System.Web.UI.WebControls.TextBox
End Class


